In [1]:
import pandas as pd

In [9]:
df = pd.read_csv(r"H:\MLOPS\MLOPS-Python\02_pandas\f500.csv")
print(df.head(2))
import numpy as np
# Renames columns
df.columns = np.arange(17)
print(df.head(2))

      company  rank  revenues  revenue_change  profits  assets  profit_change  \
0     Walmart     1    485873             0.8  13643.0  198825           -7.2
1  State Grid     2    315199            -4.4   9571.3  489838           -6.2

                   ceo               industry     sector  previous_rank  \
0  C. Douglas McMillon  General Merchandisers  Retailing              1
1              Kou Wei              Utilities     Energy              2

  country      hq_location                 website  years_on_global_500_list  \
0     USA  Bentonville, AR  http://www.walmart.com                        23
1   China   Beijing, China  http://www.sgcc.com.cn                        17

   employees  total_stockholder_equity
0    2300000                     77798
1     926067                    209456
           0   1       2    3        4       5    6                    7   \
0     Walmart   1  485873  0.8  13643.0  198825 -7.2  C. Douglas McMillon
1  State Grid   2  315199 -4.4   9571.3  489838 -6.2              Kou Wei

                      8          9   10     11               12  \
0  General Merchandisers  Retailing   1    USA  Bentonville, AR
1              Utilities     Energy   2  China   Beijing, China

                       13  14       15      16
0  http://www.walmart.com  23  2300000   77798
1  http://www.sgcc.com.cn  17   926067  209456

In [25]:
 # Checks for null Values, Returns  Boolean Array
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, np.nan, 35],
    'Country': ['USA', 'Canada', 'UK']
}
df = pd.DataFrame(data)
df.isnull()
# Show only rows with missing values
df[df.isnull().any(axis=1)]

  Name  Age Country
1  Bob  NaN  Canada

In [24]:
# Opposite of  pd.isnull()
df['Age'].notnull()

0     True
1    False
2     True
Name: Age, dtype: bool

In [26]:
# Drops all rows that contain null values
df.dropna()

      Name   Age Country
0    Alice  25.0     USA
2  Charlie  35.0      UK

In [27]:
#  Drops all columns that contain null values
df.dropna(axis=1)

      Name Country
0    Alice     USA
1      Bob  Canada
2  Charlie      UK

In [34]:
# Drops all rows have have less than  n  non-null values
df.dropna(axis = 0, thresh=30)

Empty DataFrame
Columns: [Name, Age, Country]
Index: []

In [44]:
# Replace nan with mean
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, np.nan, 35],
    'Country': ['USA', 'Canada', 'UK']
}
df = pd.DataFrame(data)
df['Age']=df['Age'].fillna(df['Age'].mean())
df

      Name   Age Country
0    Alice  25.0     USA
1      Bob  30.0  Canada
2  Charlie  35.0      UK

In [71]:
import pandas as pd
import numpy as np

s = pd.Series(np.random.randint(1,3,5), index=['a', 'b', 'c','d','e'])
s.iloc[np.random.randint(5)] = np.nan
print(s)
s.replace(1, 'one')

a    1.0
b    1.0
c    NaN
d    2.0
e    2.0
dtype: float64

a    one
b    one
c    NaN
d    2.0
e    2.0
dtype: object

In [ ]:
# Replace
s.replace([2,3],['two','three'])

a    1.0
b    1.0
c    NaN
d    two
e    two
dtype: object

In [79]:
# Rename columns
df.columns = ['a','b','c']
print(df)

         a     b       c
0    Alice  25.0     USA
1      Bob  30.0  Canada
2  Charlie  35.0      UK

In [88]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, np.nan, 35],
    'Country': ['USA', 'Canada', 'UK']
}
df = pd.DataFrame(data)
# Mass renaming of columns
df.rename(columns=lambda x: x+"_1", inplace=True)
print(df)

df.rename(columns=lambda x: x.upper(), inplace=True)
print(df)

df.columns = [f"col_{i}" for i in range(len(df.columns))]
print(df)

    Name_1  Age_1 Country_1
0    Alice   25.0       USA
1      Bob    NaN    Canada
2  Charlie   35.0        UK
    NAME_1  AGE_1 COUNTRY_1
0    Alice   25.0       USA
1      Bob    NaN    Canada
2  Charlie   35.0        UK
     col_0  col_1   col_2
0    Alice   25.0     USA
1      Bob    NaN  Canada
2  Charlie   35.0      UK

In [92]:
# selective renaming
df = df.rename(columns={'col_0' : 'Name'})
df

      Name  col_1   col_2
0    Alice   25.0     USA
1      Bob    NaN  Canada
2  Charlie   35.0      UK

In [95]:
#  Mass renaming of index
df.rename(index=lambda x : x+10, inplace=True)
df

       Name  col_1   col_2
11    Alice   25.0     USA
12      Bob    NaN  Canada
13  Charlie   35.0      UK

In [100]:
# Calculate Pearson's r correlation between revenues  and  profits  
f500 = pd.read_csv(r"H:\MLOPS\MLOPS-Python\02_pandas\f500.csv")
f500['revenues'].corr(f500['profits'])

0.432431608962067

In [108]:
# Calculate the Pearson's r correlation matrix between all columns of f500
f500.corr(numeric_only=True)

,rank,revenues,revenue_change,profits,assets,profit_change,previous_rank,years_on_global_500_list,employees,total_stockholder_equity
rank,1.000000,-0.740631,-0.011278,-0.350536,-0.310137,0.060514,0.722368,-0.369954,-0.382882,-0.435714
revenues,-0.740631,1.000000,-0.001729,0.432432,0.248759,-0.032325,-0.594854,0.267728,0.633006,0.552217
revenue_change,-0.011278,-0.001729,1.000000,-0.005058,-0.011480,0.007741,-0.073223,-0.183593,-0.072639,-0.074912
profits,-0.350536,0.432432,-0.005058,1.000000,0.517575,0.005205,-0.278180,0.129202,0.231860,0.680664
assets,-0.310137,0.248759,-0.011480,0.517575,1.000000,-0.038477,-0.242676,0.194015,0.121697,0.631838
profit_change,0.060514,-0.032325,0.007741,0.005205,-0.038477,1.000000,0.076482,0.020488,-0.040969,-0.041034
previous_rank,0.722368,-0.594854,-0.073223,-0.278180,-0.242676,0.076482,1.000000,-0.157199,-0.283356,-0.378875
years_on_global_500_list,-0.369954,0.267728,-0.183593,0.129202,0.194015,0.020488,-0.157199,1.000000,0.135613,0.222419
employees,-0.382882,0.633006,-0.072639,0.231860,0.121697,-0.040969,-0.283356,0.135613,1.000000,0.343301
total_stockholder_equity,-0.435714,0.552217,-0.074912,0.680664,0.631838,-0.041034,-0.378875,0.222419,0.343301,1.000000

In [110]:
# Calculate the correlation matrix for f500 and select the correlations for the revenues, profits, and assets columns
f500.corr(numeric_only=True)[['revenues', 'profits','assets']]

                          revenues   profits    assets
rank                     -0.740631 -0.350536 -0.310137
revenues                  1.000000  0.432432  0.248759
revenue_change           -0.001729 -0.005058 -0.011480
profits                   0.432432  1.000000  0.517575
assets                    0.248759  0.517575  1.000000
profit_change            -0.032325  0.005205 -0.038477
previous_rank            -0.594854 -0.278180 -0.242676
years_on_global_500_list  0.267728  0.129202  0.194015
employees                 0.633006  0.231860  0.121697
total_stockholder_equity  0.552217  0.680664  0.631838

In [112]:
column_data_types = f500.dtypes
print(column_data_types)

company                      object
rank                          int64
revenues                      int64
revenue_change              float64
profits                     float64
assets                        int64
profit_change               float64
ceo                          object
industry                     object
sector                       object
previous_rank                 int64
country                      object
hq_location                  object
website                      object
years_on_global_500_list      int64
employees                     int64
total_stockholder_equity      int64
dtype: object