In [1]:
import pandas as pd

In [7]:
import numpy as np
data = np.random.rand(10)
print(data)
df =  pd.DataFrame(data, columns= ['values'])
print(df)
# Rows where the values column is greater than 0.5
df[df['values'] > 0.5]

[0.30747007 0.65232022 0.19259123 0.55796833 0.52425286 0.60140346
 0.75739468 0.66681058 0.36446581 0.95503805]
     values
0  0.307470
1  0.652320
2  0.192591
3  0.557968
4  0.524253
5  0.601403
6  0.757395
7  0.666811
8  0.364466
9  0.955038

     values
1  0.652320
3  0.557968
4  0.524253
5  0.601403
6  0.757395
7  0.666811
9  0.955038

In [17]:
f500 = pd.read_csv(r'H:\MLOPS\MLOPS-Python\02_pandas\f500.csv')
print(f500.dtypes)
#  check reveune change column is greater than 1
f500['revenue_change']>1 # return boolean 
f500[f500['revenue_change']>1]

company                      object
rank                          int64
revenues                      int64
revenue_change              float64
profits                     float64
assets                        int64
profit_change               float64
ceo                          object
industry                     object
sector                       object
previous_rank                 int64
country                      object
hq_location                  object
website                      object
years_on_global_500_list      int64
employees                     int64
total_stockholder_equity      int64
dtype: object

,company,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity
4,Toyota Motor,5,254694,7.7,16899.3,437575,-12.3,Akio Toyoda,Motor Vehicles and Parts,Motor Vehicles & Parts,8,Japan,"Toyota, Japan",http://www.toyota-global.com,23,364445,157210
5,Volkswagen,6,240264,1.5,5937.3,432116,NaN,Matthias Muller,Motor Vehicles and Parts,Motor Vehicles & Parts,7,Germany,"Wolfsburg, Germany",http://www.volkswagen.com,23,626715,97753
7,Berkshire Hathaway,8,223604,6.1,24074.0,620854,NaN,Warren E. Buffett,Insurance: Property and Casualty (Stock),Financials,11,USA,"Omaha, NE",http://www.berkshirehathaway.com,21,367700,283001
10,McKesson,11,198533,3.1,5070.0,60969,124.5,John H. Hammergren,Wholesalers: Health Care,Wholesalers,12,USA,"San Francisco, CA",http://www.mckesson.com,23,64500,11095
12,UnitedHealth Group,13,184840,17.7,7017.0,122810,20.7,Stephen J. Hemsley,Health Care: Insurance and Managed Care,Health Care,17,USA,"Minnetonka, MN",http://www.unitedhealthgroup.com,21,230000,38274
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,Dollar General,492,21987,7.9,1251.1,11672,7.4,Todd J. Vasos,Specialty Retailers,Retailing,0,USA,"Goodlettsville, TN",http://www.dollargeneral.com,1,121000,5406
493,Xiamen ITG Holding Group,494,21930,34.3,35.6,12161,-25.1,Xu Xiaoxi,Trading,Wholesalers,0,China,"Xiamen, China",http://www.itgholding.com.cn,1,18454,1066
494,Xinjiang Guanghui Industry Investment,495,21919,31.1,251.8,31957,49.9,Shang Jiqiang,Trading,Wholesalers,0,China,"Urumqi, China",http://www.guanghui.com,1,65616,4563
495,Teva Pharmaceutical Industries,496,21903,11.5,329.0,92890,-79.3,Yitzhak Peterburg,Pharmaceuticals,Health Care,0,Israel,"Petach Tikva, Israel",http://www.tevapharm.com,1,56960,33337
499,AutoNation,500,21609,3.6,430.5,10060,-2.7,Michael J. Jackson,Specialty Retailers,Retailing,0,USA,"Fort Lauderdale, FL",http://www.autonation.com,12,26000,2310

In [19]:
# Revenue change greater than 2 but less than 10
f500[(f500['revenue_change'] > 2) & (f500['revenue_change'] <10)]

,company,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity
4,Toyota Motor,5,254694,7.7,16899.3,437575,-12.3,Akio Toyoda,Motor Vehicles and Parts,Motor Vehicles & Parts,8,Japan,"Toyota, Japan",http://www.toyota-global.com,23,364445,157210
7,Berkshire Hathaway,8,223604,6.1,24074.0,620854,NaN,Warren E. Buffett,Insurance: Property and Casualty (Stock),Financials,11,USA,"Omaha, NE",http://www.berkshirehathaway.com,21,367700,283001
10,McKesson,11,198533,3.1,5070.0,60969,124.5,John H. Hammergren,Wholesalers: Health Care,Wholesalers,12,USA,"San Francisco, CA",http://www.mckesson.com,23,64500,11095
16,Daimler,17,169483,2.2,9428.4,256262,0.9,Dieter Zetsche,Motor Vehicles and Parts,Motor Vehicles & Parts,16,Germany,"Stuttgart, Germany",http://www.daimler.com,23,282488,61116
17,General Motors,18,166380,9.2,9427.0,221690,-2.7,Mary T. Barra,Motor Vehicles and Parts,Motor Vehicles & Parts,20,USA,"Detroit, MI",http://www.gm.com,23,225000,43836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482,Aflac,483,22559,8.1,2659.0,129819,5.0,Daniel P. Amos,"Insurance: Life, Health (stock)",Financials,0,USA,"Columbus, GA",http://www.aflac.com,10,10212,20482
484,Suning Commerce Group,485,22366,3.7,106.0,19738,-23.6,Ren Jun,Specialty Retailers,Retailing,0,China,"Nanjing, China",http://www.suning.com,1,60354,9455
487,Xiamen C&D,488,22145,6.6,280.2,21729,15.6,Huang Wenzhou,Trading,Wholesalers,0,China,"Xiamen, China",http://www.chinacdc.com,1,18381,3985
491,Dollar General,492,21987,7.9,1251.1,11672,7.4,Todd J. Vasos,Specialty Retailers,Retailing,0,USA,"Goodlettsville, TN",http://www.dollargeneral.com,1,121000,5406
499,AutoNation,500,21609,3.6,430.5,10060,-2.7,Michael J. Jackson,Specialty Retailers,Retailing,0,USA,"Fort Lauderdale, FL",http://www.autonation.com,12,26000,2310

In [27]:
# Sorts values by revenue change in ascending order
f500_assending = f500.sort_values('revenue_change')
print(f"ascending order: {f500_assending.head(5)}")

ascending order:           company  rank  revenues  revenue_change  profits  assets  \
230          E.ON   231     42213           -67.3  -9344.4   67179
193            HP   194     48238           -53.3   2496.0   29010
349  BHP Billiton   350     30912           -40.9  -6385.0  118953
131           ENI   132     62694           -32.6  -1619.0  131349
204   Noble Group   205     46528           -30.3      8.7   12285

     profit_change                 ceo                      industry  \
230            NaN    Johannes Teyssen                        Energy
193          -45.2     Dion J. Weisler   Computers, Office Equipment
349         -434.3    Andrew Mackenzie  Mining, Crude-Oil Production
131            NaN    Claudio Descalzi            Petroleum Refining
204            NaN  William J. Randall                       Trading

          sector  previous_rank    country           hq_location  \
230       Energy             32    Germany        Essen, Germany
193   Technology             48        USA         Palo Alto, CA
349       Energy            168  Australia  Melbourne, Australia
131       Energy             65      Italy           Rome, Italy
204  Wholesalers            116      China      Hong Kong, China

                        website  years_on_global_500_list  employees  \
230          http://www.eon.com                        23      43138
193           http://www.hp.com                        23      49000
349  http://www.bhpbilliton.com                        23      26827
131          http://www.eni.com                        23      33536
204  http://www.thisisnoble.com                        10       1000

     total_stockholder_equity
230                     -1113
193                     -3889
349                     54290
131                     55934
204                      3974

In [ ]:
#  Sorts values by revenue change in descending order
f500_desencing = f500.sort_values('revenue_change', ascending=False)
print(f" Descending order: {f500_desencing.head(5)}")

 Descending order:                     company  rank  revenues  revenue_change  profits  assets  \
48    Legal & General Group    49    105235           442.3   1697.9  577954
375  Charter Communications   376     29003           197.3   3522.0  149067
138  Anbang Insurance Group   139     60800           124.0   3883.9  430040
94              SK Holdings    95     72579           107.4    659.7   85332
89                    Aviva    90     74628           105.9    948.8  544063

     profit_change                 ceo                          industry  \
48             3.4        Nigel Wilson   Insurance: Life, Health (stock)
375            NaN  Thomas M. Rutledge                Telecommunications
138            0.9          Wu Xiaohui  Insurance: Life, Health (Mutual)
94           -86.0        Tae Won Chey                Petroleum Refining
89           -32.3         Mark Wilson   Insurance: Life, Health (stock)

                 sector  previous_rank      country         hq_location  \
48           Financials              0      Britain     London, Britain
375  Telecommunications              0          USA        Stamford, CT
138          Financials              0        China      Beijing, China
94               Energy            294  South Korea  Seoul, South Korea
89           Financials            279      Britain     London, Britain

                                 website  years_on_global_500_list  employees  \
48   http://www.legalandgeneralgroup.com                        17       8939
375               http://www.charter.com                         1      91500
138           http://www.anbanggroup.com                         1      40707
94                   http://www.sk.co.kr                         2      84000
89                  http://www.aviva.com                        23      29530

     total_stockholder_equity
48                       8579
375                     40139
138                     20372
94                      10858
89                      21004

In [ ]:
# Sorts values by revenue change in ascending & descending order
f500.dtypes
f500.sort_values(['revenue_change', 'profits'], ascending=[True,False])

,company,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity
230,E.ON,231,42213,-67.3,-9344.4,67179,NaN,Johannes Teyssen,Energy,Energy,32,Germany,"Essen, Germany",http://www.eon.com,23,43138,-1113
193,HP,194,48238,-53.3,2496.0,29010,-45.2,Dion J. Weisler,"Computers, Office Equipment",Technology,48,USA,"Palo Alto, CA",http://www.hp.com,23,49000,-3889
349,BHP Billiton,350,30912,-40.9,-6385.0,118953,-434.3,Andrew Mackenzie,"Mining, Crude-Oil Production",Energy,168,Australia,"Melbourne, Australia",http://www.bhpbilliton.com,23,26827,54290
131,ENI,132,62694,-32.6,-1619.0,131349,NaN,Claudio Descalzi,Petroleum Refining,Energy,65,Italy,"Rome, Italy",http://www.eni.com,23,33536,55934
204,Noble Group,205,46528,-30.3,8.7,12285,NaN,William J. Randall,Trading,Wholesalers,116,China,"Hong Kong, China",http://www.thisisnoble.com,10,1000,3974
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,Anbang Insurance Group,139,60800,124.0,3883.9,430040,0.9,Wu Xiaohui,"Insurance: Life, Health (Mutual)",Financials,0,China,"Beijing, China",http://www.anbanggroup.com,1,40707,20372
375,Charter Communications,376,29003,197.3,3522.0,149067,NaN,Thomas M. Rutledge,Telecommunications,Telecommunications,0,USA,"Stamford, CT",http://www.charter.com,1,91500,40139
48,Legal & General Group,49,105235,442.3,1697.9,577954,3.4,Nigel Wilson,"Insurance: Life, Health (stock)",Financials,0,Britain,"London, Britain",http://www.legalandgeneralgroup.com,17,8939,8579
180,Hewlett Packard Enterprise,181,50123,NaN,3161.0,79679,NaN,Margaret C. Whitman,Information Technology Services,Technology,0,USA,"Palo Alto, CA",http://www.hpe.com,1,195000,31448
90,Uniper,91,74407,NaN,-3557.5,51541,NaN,Klaus Schafer,Energy,Energy,0,Germany,"Dusseldorf, Germany",http://www.uniper.energy,1,12890,12889

In [45]:
f500.groupby('revenue_change')
f500.groupby('revenue_change').mean(numeric_only=True)
f500.groupby(['revenue_change' ,'profits']).mean(numeric_only=True)

,,rank,revenues,assets,profit_change,previous_rank,years_on_global_500_list,employees,total_stockholder_equity
revenue_change,profits,,,,,,,,
-67.3,-9344.4,231.0,42213.0,67179.0,NaN,32.0,23.0,43138.0,-1113.0
-53.3,2496.0,194.0,48238.0,29010.0,-45.2,48.0,23.0,49000.0,-3889.0
-40.9,-6385.0,350.0,30912.0,118953.0,-434.3,168.0,23.0,26827.0,54290.0
-32.6,-1619.0,132.0,62694.0,131349.0,NaN,65.0,23.0,33536.0,55934.0
-30.3,8.7,205.0,46528.0,12285.0,NaN,116.0,10.0,1000.0,3974.0
...,...,...,...,...,...,...,...,...,...
105.9,948.8,90.0,74628.0,544063.0,-32.3,279.0,23.0,29530.0,21004.0
107.4,659.7,95.0,72579.0,85332.0,-86.0,294.0,2.0,84000.0,10858.0
124.0,3883.9,139.0,60800.0,430040.0,0.9,0.0,1.0,40707.0,20372.0
197.3,3522.0,376.0,29003.0,149067.0,NaN,0.0,1.0,91500.0,40139.0
442.3,1697.9,49.0,105235.0,577954.0,3.4,0.0,17.0,8939.0,8579.0

In [46]:
import pandas as pd

data = {
    'Company': ['A', 'B', 'C', 'D', 'E'],
    'Sector': ['Tech', 'Finance', 'Tech', 'Finance', 'Tech'],
    'Country': ['USA', 'USA', 'UK', 'UK', 'USA'],
    'Revenue': [100, 200, 150, 120, 180]
}

df = pd.DataFrame(data)
print(df)

  Company   Sector Country  Revenue
0       A     Tech     USA      100
1       B  Finance     USA      200
2       C     Tech      UK      150
3       D  Finance      UK      120
4       E     Tech     USA      180

In [48]:
# Group by Sector and calculate average revenue:
df.groupby('Sector')['Revenue'].mean()

Sector
Finance    160.000000
Tech       143.333333
Name: Revenue, dtype: float64

In [49]:
# Group by Sector + Country
df.groupby(['Sector', 'Country'])['Revenue'].mean()

Sector   Country
Finance  UK         120.0
         USA        200.0
Tech     UK         150.0
         USA        140.0
Name: Revenue, dtype: float64

In [50]:
# Pivot Table
pd.pivot_table(df, 
               values='Revenue', 
               index='Sector', 
               columns='Country', 
               aggfunc='sum')

Country   UK  USA
Sector
Finance  120  200
Tech     150  280

In [53]:
import numpy as np
df.groupby('Sector').agg({'Revenue': 'mean'})

            Revenue
Sector
Finance  160.000000
Tech     143.333333

In [56]:
df.select_dtypes(include='number').apply(np.mean)

Revenue    150.0
dtype: float64

In [61]:
data1 = np.arange(1,10,1)
df1 = pd.DataFrame(data1)
print(df1)
data2 = np.array([60,70,80])
df2 = pd.DataFrame(data2)
print(df2)
result = pd.concat([df1, df2])
print(result)

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8
8  9
    0
0  60
1  70
2  80
    0
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
0  60
1  70
2  80