In [1]:
import pandas as pd
import numpy as np

In [ ]:
# Q1. Load a CSV file into a DataFrame. Write code to: 
# (a) View first 10 rows 
# (b) Get shape 
# (c) View data types
df = pd.read_csv(r"H:\MLOPS\MLOPS-Python\02_pandas\f500.csv")
print(f"View first 10 rows:\n{df.head(10)}")
print(f"shape of the dataframe:\n{np.shape(df)}")
print(df.dtypes)

company                      object
rank                          int64
revenues                      int64
revenue_change              float64
profits                     float64
assets                        int64
profit_change               float64
ceo                          object
industry                     object
sector                       object
previous_rank                 int64
country                      object
hq_location                  object
website                      object
years_on_global_500_list      int64
employees                     int64
total_stockholder_equity      int64
dtype: object

In [27]:
# Q2. Write code to select: (a) Column 'revenues' (b) Columns 'country' and 'profit'
print(f"Revenue:\n {df[["revenues"]]}")
print(f"country and profit:\n {df[["country","profits"]]}")

Revenue:
      revenues
0      485873
1      315199
2      267518
3      262573
4      254694
..        ...
495     21903
496     21796
497     21741
498     21655
499     21609

[500 rows x 1 columns]
country and profit:
      country  profits
0        USA  13643.0
1      China   9571.3
2      China   1257.9
3      China   1867.5
4      Japan  16899.3
..       ...      ...
495   Israel    329.0
496    China    743.9
497  Britain    406.4
498  Germany   1151.7
499      USA    430.5

[500 rows x 2 columns]

In [36]:
# Q3. Filter rows where revenue > 100000 and profit < 0.
df[(df['revenues'] >10000) & (df["profits"] <0)]

,company,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity
32,Japan Post Holdings,33,122990,3.6,-267.4,2631385,-107.5,Masatsugu Nagato,"Insurance: Life, Health (stock)",Financials,37,Japan,"Tokyo, Japan",http://www.japanpost.jp,21,248384,91532
44,Chevron,45,107567,-18.0,-497.0,260078,-110.8,John S. Watson,Petroleum Refining,Energy,31,USA,"San Ramon, CA",http://www.chevron.com,23,55200,145556
74,Petrobras,75,81405,-16.3,-4838.0,246983,NaN,Pedro Pullen Parente,Petroleum Refining,Energy,58,Brazil,"Rio de Janeiro, Brazil",http://www.petrobras.com.br,23,68829,76779
90,Uniper,91,74407,NaN,-3557.5,51541,NaN,Klaus Schafer,Energy,Energy,0,Germany,"Dusseldorf, Germany",http://www.uniper.energy,1,12890,12889
91,Tesco,92,74393,-15.1,-52.7,57052,-125.3,David J. Lewis,Food and Drug Stores,Food & Drug Stores,72,Britain,"Welwyn Garden City, Britain",http://www.tescoplc.com,23,342770,8011
92,Engie,93,73692,-4.9,-458.9,167158,NaN,Isabelle Kocher,Energy,Energy,89,France,"Courbevoie, France",http://www.engie.com,22,153090,41740
98,U.S. Postal Service,99,71498,3.7,-5591.0,25219,NaN,Megan J. Brennan,"Mail, Package, and Freight Delivery",Transportation,107,USA,"Washington, DC",http://www.usps.com,23,574349,-55982
119,China Minmetals,120,65547,105.6,-446.7,109334,NaN,He Wenbo,Metals,Materials,323,China,"Beijing, China",http://www.minmetals.com,11,212406,4631
123,Dell Technologies,124,64806,18.1,-1672.0,118206,NaN,Michael S. Dell,"Computers, Office Equipment",Technology,0,USA,"Round Rock, TX",http://www.delltechnologies.com,17,138000,13243
131,ENI,132,62694,-32.6,-1619.0,131349,NaN,Claudio Descalzi,Petroleum Refining,Energy,65,Italy,"Rome, Italy",http://www.eni.com,23,33536,55934
140,Albertsons Cos.,141,59678,1.6,-373.3,23755,NaN,Robert G. Miller,Food and Drug Stores,Food & Drug Stores,0,USA,"Boise, ID",http://www.albertsons.com,13,273000,1371
148,Vodafone Group,149,58611,-5.0,-6904.0,165420,NaN,Vittorio Colao,Telecommunications,Telecommunications,133,Britain,"Newbury, Britain",http://www.vodafone.com,18,111556,77211
151,Pemex,152,57774,-21.4,-10256.3,113115,NaN,Jose Antonio Gonzalez Anaya,"Mining, Crude-Oil Production",Energy,98,Mexico,"Mexico City, Mexico",http://www.pemex.com,23,125689,-59909
174,AIG,175,52367,-10.2,-849.0,498264,-138.7,Brian Duperreault,Insurance: Property and Casualty (Stock),Financials,150,USA,"New York, NY",http://www.aig.com,22,56400,76300
188,Deutsche Bank,189,48876,-6.8,-1550.4,1677437,NaN,John Cryan,Banks: Commercial and Savings,Financials,166,Germany,"Frankfurt, Germany",http://www.db.com,23,99744,63102
194,RWE,195,48204,-6.6,-6249.1,80576,NaN,Rolf Martin Schmitz,Utilities,Energy,174,Germany,"Essen, Germany",http://www.rwe.com,23,58652,3898
206,Statoil,207,45873,-23.4,-2902.0,104530,NaN,Eldar Saetre,Petroleum Refining,Energy,145,Norway,"Stavanger, Norway",http://www.statoil.com,23,20539,35072
217,Woolworths,218,43925,-13.2,-898.3,17495,-150.3,Brad Banducci,Food and Drug Stores,Food & Drug Stores,176,Australia,"Bella Vista, Australia",http://www.woolworthslimited.com.au,21,205000,6305
220,HBIS Group,221,43769,-3.3,-146.8,51858,NaN,Yu Yong,Metals,Materials,201,China,"Shijiazhuang, China",http://www.hbisco.com,9,125552,7693
230,E.ON,231,42213,-67.3,-9344.4,67179,NaN,Johannes Teyssen,Energy,Energy,32,Germany,"Essen, Germany",http://www.eon.com,23,43138,-1113
247,Aluminum Corp. of China,248,40278,6.0,-282.5,75089,NaN,Yu Dehui,Metals,Materials,262,China,"Beijing, China",http://www.chalco.com.cn,10,121146,2669
260,JD.com,261,39155,35.7,-573.0,23077,NaN,Richard Qiangdong Liu,Internet Services and Retailing,Technology,366,China,"Beijing, China",http://www.jd.com,2,120622,4877
263,Caterpillar,264,38537,-18.0,-67.0,74704,-103.2,D. James Umpleby III,Construction and Farm Machinery,Industrials,194,USA,"Peoria, IL",http://www.caterpillar.com,23,95400,13137
271,Johnson Controls International,272,37674,-6.3,-868.0,63253,-155.5,Alex A. Molinaroli,Industrial Machinery,Industrials,0,Ireland,"Cork, Ireland",http://www.johnsoncontrols.com,13,209000,24118
273,China Huaneng Group,274,37543,-13.1,-85.9,144306,-111.1,Cao Peixi,Energy,Energy,217,China,"Beijing, China",http://www.chng.com.cn,9,143691,7512
297,Maersk Group,298,35464,-12.0,-1939.0,61118,-345.1,Soren Skou,Shipping,Transportation,240,Denmark,"Copenhagen, Denmark",http://www.maersk.com,14,87736,31258
319,Jizhong Energy Group,320,33366,-11.8,-153.9,30819,NaN,Yang GuoZhan,"Mining, Crude-Oil Production",Energy,267,China,"Xingtai, China",http://www.jznyjt.com,7,127298,2042
325,Shaanxi Yanchang Petroleum (Group),326,32652,2.8,-22.6,45552,NaN,He Jiuchang,"Mining, Crude-Oil Production",Energy,325,China,"Xi'an, China",http://www.sxycpc.com,5,134134,14063
327,UniCredit Group,328,32539,-5.9,-13038.0,906489,-793.7,Jean Pierre Mustier,Banks: Commercial and Savings,Financials,300,Italy,"Milan, Italy",http://www.unicreditgroup.eu,22,117659,41484
336,Shaanxi Coal & Chemical Industry,337,31926,5.3,-254.4,64151,NaN,Yang Zhaoqian,"Mining, Crude-Oil Production",Energy,347,China,"Xi'an, China",http://www.shccig.com,3,123559,5769
349,BHP Billiton,350,30912,-40.9,-6385.0,118953,-434.3,Andrew Mackenzie,"Mining, Crude-Oil Production",Energy,168,Australia,"Melbourne, Australia",http://www.bhpbilliton.com,23,26827,54290
353,Credit Suisse Group,354,30588,-13.0,-2750.7,806950,NaN,Tidjane Thiam,Banks: Commercial and Savings,Financials,292,Switzerland,"Zurich, Switzerland",http://www.credit-suisse.com,23,47170,41237
387,Schlumberger,388,27810,-21.6,-1687.0,77956,-181.4,Paal Kibsgaard,Oil & Gas Equipment Services,Energy,287,USA,"Houston, TX",http://www.slb.com,17,100000,41078
408,Achmea,409,26494,2.8,-423.5,98096,-199.7,Willem A.J. van Duin,"Insurance: Life, Health (Mutual)",Financials,413,Netherlands,"Zeist, Netherlands",http://www.achmea.nl,4,14921,10308
414,Nokia,415,26113,73.4,-847.1,47354,-131.0,Rajeev Suri,Network and Other Communications Equipment,Technology,0,Finland,"Espoo, Finland",http://www.nokia.com,19,102687,21192
429,Datong Coal Mine Group,430,25630,-19.8,-214.8,40012,NaN,Zhang Youxi,"Mining, Crude-Oil Production",Energy,322,China,"Datong, China",http://www.dtcoalmine.com,5,162542,3169
432,Shanxi Coking Coal Group,433,25123,-19.1,-10.0,39206,-113.1,Wu Huatai,"Mining, Crude-Oil Production",Energy,337,China,"Taiyuan, China",http://www.sxcc.com.cn,5,209817,4318
443,ConocoPhillips,444,24360,-21.3,-3615.0,89772,NaN,Ryan M. Lance,"Mining, Crude-Oil Production",Energy,339,USA,"Houston, TX",http://www.conocophillips.com,23,13300,34974
447,Shanxi LuAn Mining Group,448,24087,-15.9,-106.9,29026,NaN,Li Jinping,"Mining, Crude-Oil Production",Energy,370,China,"Changzhi, China",http://www.chinaluan.com,5,95666,2542
472,Altice,473,22953,42.2,-1722.5,84805,NaN,Michel Combes,Telecommunications,Telecommunications,0,Netherlands,"Amsterdam, Netherlands",http://www.altice.net,1,49732,-2668
473,Onex,474,22943,3.8,-130.0,42913,NaN,Gerald W. Schwartz,Semiconductors and Other Electronic Components,Technology,483,Canada,"Toronto, Ontario, Canada",http://www.onex.com,18,161000,-490
488,Sears Holdings,489,22138,-12.0,-2221.0,9362,NaN,Edward S. Lampert,General Merchandisers,Retailing,425,USA,"Hoffman Estates, IL",http://www.searsholdings.com,23,140000,-3824

In [47]:
# Q4. In column 'employees': (a) Count null values (b) Replace nulls with mean
df1 = df['employees'].notnull().value_counts()
df['employees'] = df['employees'].fillna(df['employees'].mean())
df

,company,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity
0,Walmart,1,485873,0.8,13643.0,198825,-7.2,C. Douglas McMillon,General Merchandisers,Retailing,1,USA,"Bentonville, AR",http://www.walmart.com,23,2300000,77798
1,State Grid,2,315199,-4.4,9571.3,489838,-6.2,Kou Wei,Utilities,Energy,2,China,"Beijing, China",http://www.sgcc.com.cn,17,926067,209456
2,Sinopec Group,3,267518,-9.1,1257.9,310726,-65.0,Wang Yupu,Petroleum Refining,Energy,4,China,"Beijing, China",http://www.sinopec.com,19,713288,106523
3,China National Petroleum,4,262573,-12.3,1867.5,585619,-73.7,Zhang Jianhua,Petroleum Refining,Energy,3,China,"Beijing, China",http://www.cnpc.com.cn,17,1512048,301893
4,Toyota Motor,5,254694,7.7,16899.3,437575,-12.3,Akio Toyoda,Motor Vehicles and Parts,Motor Vehicles & Parts,8,Japan,"Toyota, Japan",http://www.toyota-global.com,23,364445,157210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Teva Pharmaceutical Industries,496,21903,11.5,329.0,92890,-79.3,Yitzhak Peterburg,Pharmaceuticals,Health Care,0,Israel,"Petach Tikva, Israel",http://www.tevapharm.com,1,56960,33337
496,New China Life Insurance,497,21796,-13.3,743.9,100609,-45.6,Wan Feng,"Insurance: Life, Health (stock)",Financials,427,China,"Beijing, China",http://www.newchinalife.com,2,54378,8507
497,Wm. Morrison Supermarkets,498,21741,-11.3,406.4,11630,20.4,David T. Potts,Food and Drug Stores,Food & Drug Stores,437,Britain,"Bradford, Britain",http://www.morrisons.com,13,77210,5111
498,TUI,499,21655,-5.5,1151.7,16247,195.5,Friedrich Joussen,Travel Services,Business Services,467,Germany,"Hanover, Germany",http://www.tuigroup.com,23,66779,3006
499,AutoNation,500,21609,3.6,430.5,10060,-2.7,Michael J. Jackson,Specialty Retailers,Retailing,0,USA,"Fort Lauderdale, FL",http://www.autonation.com,12,26000,2310

In [62]:
# Q5. Group by 'country' and compute average revenue.
df = pd.read_csv(r'H:\MLOPS\MLOPS-Python\02_pandas\f500.csv')
df.groupby(['country'])['revenues'].mean()

country
Australia       33688.714286
Belgium         45905.000000
Brazil          52024.571429
Britain         51588.708333
Canada          31848.000000
China           55397.880734
Denmark         35464.000000
Finland         26113.000000
France          55231.793103
Germany         63915.000000
India           39993.000000
Indonesia       36487.000000
Ireland         32819.500000
Israel          21903.000000
Italy           51899.571429
Japan           53164.039216
Luxembourg      56791.000000
Malaysia        49479.000000
Mexico          54987.500000
Netherlands     61708.928571
Norway          45873.000000
Russia          65247.750000
Saudi Arabia    35421.000000
Singapore       54454.333333
South Korea     49725.600000
Spain           40600.666667
Sweden          27963.666667
Switzerland     51353.571429
Taiwan          46364.666667
Thailand        48719.000000
Turkey          23456.000000
U.A.E           22799.000000
USA             64218.371212
Venezuela       24403.000000
Name: revenues, dtype: float64

In [63]:
# Q6. Sort by 'revenues' descending and 'profits' ascending.
df.sort_values(['revenues','profits'], ascending=[False,True])

,company,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity
0,Walmart,1,485873,0.8,13643.0,198825,-7.2,C. Douglas McMillon,General Merchandisers,Retailing,1,USA,"Bentonville, AR",http://www.walmart.com,23,2300000,77798
1,State Grid,2,315199,-4.4,9571.3,489838,-6.2,Kou Wei,Utilities,Energy,2,China,"Beijing, China",http://www.sgcc.com.cn,17,926067,209456
2,Sinopec Group,3,267518,-9.1,1257.9,310726,-65.0,Wang Yupu,Petroleum Refining,Energy,4,China,"Beijing, China",http://www.sinopec.com,19,713288,106523
3,China National Petroleum,4,262573,-12.3,1867.5,585619,-73.7,Zhang Jianhua,Petroleum Refining,Energy,3,China,"Beijing, China",http://www.cnpc.com.cn,17,1512048,301893
4,Toyota Motor,5,254694,7.7,16899.3,437575,-12.3,Akio Toyoda,Motor Vehicles and Parts,Motor Vehicles & Parts,8,Japan,"Toyota, Japan",http://www.toyota-global.com,23,364445,157210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Teva Pharmaceutical Industries,496,21903,11.5,329.0,92890,-79.3,Yitzhak Peterburg,Pharmaceuticals,Health Care,0,Israel,"Petach Tikva, Israel",http://www.tevapharm.com,1,56960,33337
496,New China Life Insurance,497,21796,-13.3,743.9,100609,-45.6,Wan Feng,"Insurance: Life, Health (stock)",Financials,427,China,"Beijing, China",http://www.newchinalife.com,2,54378,8507
497,Wm. Morrison Supermarkets,498,21741,-11.3,406.4,11630,20.4,David T. Potts,Food and Drug Stores,Food & Drug Stores,437,Britain,"Bradford, Britain",http://www.morrisons.com,13,77210,5111
498,TUI,499,21655,-5.5,1151.7,16247,195.5,Friedrich Joussen,Travel Services,Business Services,467,Germany,"Hanover, Germany",http://www.tuigroup.com,23,66779,3006
499,AutoNation,500,21609,3.6,430.5,10060,-2.7,Michael J. Jackson,Specialty Retailers,Retailing,0,USA,"Fort Lauderdale, FL",http://www.autonation.com,12,26000,2310